@startuml

class RenderContext {
  gl: WebGLRenderingContext
  sharedAttributes: Object<String, uint>
  shaders: Object<String, Shader>
}

class Shader {
  context: RenderContext
  vertexShader: WebGLShader
  fragmentShader: WebGLShader
  program: WebGLProgram
  isShared: Boolean
  ---
  name: String
  attributes: Object<String, uint>
  uniforms: Object<String, uint>
  attributeTypes: Object<String, uint>
  uniformTypes: Object<String, uint>
}

class Texture {
  context: RenderContext
  texture: WebGLTexture
  ---
  name: String
}

class Texture2D {
  image: HTMLImageElement
}

class TextureCube {
  images: Array<HTMLImageElement>
}

Texture2D --|> Texture
TextureCube --|> Texture

class Material {
  shader: String | Shader
  texture: String | Texture
}

Shader --* Material
Texture --* Material

class Geometry {
  context: RenderContext
  vbo: WebGLBuffer
  vba: Object<String, WebGLBuffer>
  ---
  indices: Uint16Array | Uint8Array
  type: String
}

class 2DGeometry {
  vertices: Float32Array
  texCoords: Float32Array
}

class 3DGeometry {
  vertices: Float32Array
  normals: Float32Array
  tangents: Float32Array
  texCoords: Float32Array
}

2DGeometry --|> Geometry
3DGeometry --|> Geometry

class WireframeGeometry {
  geometry: Geometry
}

WireframeGeometry --|> Geometry

class Transform {
  position: Float32Array
  rotation: Float32Array
  scale: Float32Array
}

class Object3D {
  transform: Transform
}

Transform --o Object3D

class Mesh {
  material: Material
  geometry: Geometry
}

Mesh -|> Object3D
Geometry --* Mesh
Material --* Mesh

@enduml
